[general]
import = [
  "~/.config/alacritty/colors/base16-gruvbox-dark-hard.toml",
]

[window]
decorations = "Buttonless" # macOS exclusive
option_as_alt = "Both" # macOS exclusive
opacity = 1.0
blur = true

[scrolling]
history = 0 # I'm in tmux all the time

[font]
# normal = { family = "Iosevka Term SS09", style = "Extended" }
# bold = { family = "Iosevka Term SS09", style = "Bold Extended" }
# italic = { family = "Iosevka Term SS09", style = "Extended Italic" }
# bold_italic = { family = "Iosevka Term SS09", style = "Bold Extended Italic" }
normal = { family = "Hack Nerd Font" }
size = 13.5
offset = { y = 3 }

[colors]
transparent_background_colors = true

[mouse]
# temporarily hide mouse cursor when typing
hide_when_typing = true
# disable default mouse bindings
bindings = [
  { mouse = "Left", action = "None" },
  { mouse = "Right", action = "ReceiveChar" },
  { mouse = "Right", mods = "Control", action = "ReceiveChar" },
]

[keyboard]
# disable a bunch of default keybindings
bindings = [
  #{ key = "Paste", action = "ReceiveChar" },
  #{ key = "Copy", action = "ReceiveChar" },
  { key = "L", mods = "Control", action = "ReceiveChar" },
  { key = "L", mods = "Control", mode = "~Vi|~Search", action = "ReceiveChar" },
  # vi mode
  { key = "Space", mods = "Shift|Control", mode = "~Search", action = "ReceiveChar" },
  # macOS exclusive
  { key = "K", mods = "Command", mode = "~Vi|~Search", action = "ReceiveChar" },
  # { key = "0", mods = "Command", action = "ReceiveChar" },
  #{ key = "=", mods = "Command", action = "ReceiveChar" },
  #{ key = "+", mods = "Command", action = "ReceiveChar" },
  #{ key = "NumpadAdd", mods = "Command", action = "ReceiveChar" },
  #{ key = "-", mods = "Command", action = "ReceiveChar" },
  #{ key = "NumpadSubtract", mods = "Command", action = "ReceiveChar" },
  #{ key = "V", mods = "Command", mode = "~Vi", action = "ReceiveChar" },
  #{ key = "C", mods = "Command", action = "ReceiveChar" },
  { key = "H", mods = "Command", action = "ReceiveChar" },
  { key = "H", mods = "Command|Alt", action = "ReceiveChar" },
  { key = "M", mods = "Command", action = "ReceiveChar" },
  { key = "Q", mods = "Command", action = "ReceiveChar" },
  { key = "W", mods = "Command", action = "ReceiveChar" },
  { key = "N", mods = "Command", action = "ReceiveChar" },
  { key = "T", mods = "Command", action = "ReceiveChar" },
  { key = "F", mods = "Command|Control", action = "ReceiveChar" },
  { key = "F", mods = "Command", mode = "~Search", action = "ReceiveChar" },
  { key = "B", mods = "Command", mode = "~Search", action = "ReceiveChar" },
  { key = "]", mods = "Command|Shift", action = "ReceiveChar" },
  { key = "[", mods = "Command|Shift", action = "ReceiveChar" },
  { key = "Tab", mods = "Command", action = "ReceiveChar" },
  { key = "Tab", mods = "Command|Shift", action = "ReceiveChar" },
  { key = "1", mods = "Command", action = "ReceiveChar" },
  { key = "2", mods = "Command", action = "ReceiveChar" },
  { key = "3", mods = "Command", action = "ReceiveChar" },
  { key = "4", mods = "Command", action = "ReceiveChar" },
  { key = "5", mods = "Command", action = "ReceiveChar" },
  { key = "6", mods = "Command", action = "ReceiveChar" },
  { key = "7", mods = "Command", action = "ReceiveChar" },
  { key = "8", mods = "Command", action = "ReceiveChar" },
  { key = "9", mods = "Command", action = "ReceiveChar" },
]
